spring:
  datasource:
    url: jdbc:mysql://localhost:3306/saham_hr_db_test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: medjool

  jpa:
    hibernate:
      ddl-auto: update

  main:
    allow-bean-definition-overriding: true
file:
  upload:
    medical-certificates: src/main/resources/folders
    payrolls: src/main/resources/payrolls

