# Application configuration for staging environment
spring:
  application:
    name: hr_system
  # Database Configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/saham_hr_db_staging?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: :${DB_PASSWORD}

  flyway:
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    enabled: true
    url: jdbc:mysql://localhost:3306/saham_hr_db_staging

  jpa:
    hibernate:
      ddl-auto: validate
  main:
    lazy-initialization: true

# Server Configuration
server:
  port: 8081
  address: 0.0.0.0
# File Storage Configuration
file:
  upload:
    medical-certificates: ${MEDICAL_CERTIFICATES_PATH}
    payrolls: ${PAYROLLS_PATH}
# JWT Secret
secret:
  key: ${JWT_SECRET_KEY}

# Email Configuration
outlook:
  tenant-id: ${TENANT_ID}
  client-id: ${CLIENT_ID}
  user-email: ${USER_EMAIL}
  client-secret: ${EMAIL_CLIENT_SECRET}